UG_MAJORS = [
"Accounting (BS)",
"African American and African Diaspora Studies (BA)",
"American Studies (BA)",
"Anthropology (BA)",
"Applied Mathematics (BS)",
"Arab World Studies (BA)",
"Arabic Studies (BA)",
"Art History (BA)",
"Asia, Pacific, and Diaspora Studies (BA)",
"Audio Production (BA)",
"Audio Technology (BS)",
"Biochemistry (BS)",
"Biology (BS)",
"Business Administration (BSBA)",
"Business and Entertainment (BS)",
"Business, Language & Culture Studies (BS)",
"Chemistry (BS)",
"Chinese Studies (BA)",
"Communication, Language, and Culture (BA) [CAS/WLC]",
"Communication, Language, and Culture (BA) [SOC]",
"Communication: Communication Studies (BA)",
"Communication: Film and Media Arts (BA)",
"Communication: Journalism (BA)",
"Computational Media and Applied Perception (BA)",
"Computational Science (BS) [CAS/CSC]",
"Computational Science (BS) [CAS/MATH]",
"Computer Science (BA)",
"Computer Science (BS)",
"Dance (BA)",
"Data Science (BS)",
"Data Sciences for Justice, Law and Criminology (BS)",
"Data Sciences for Political Science (BS)",
"Early Childhood Education (BA)",
"Economics (BA)",
"Economics (BS)",
"Elementary Education (BA)",
"Environmental Science (BS)",
"Environmental Studies (BA)",
"Finance (BS)",
"French Studies (BA)",
"German Studies (BA)",
"Global International Relations (BA)",
"Graphic and Visual Communication Design (BA)",
"Health Promotion (BS)",
"History (BA)",
"Interdisciplinary Studies: Communication, Legal Institutions, Economics, and Government (CLEG) (BA)",
"International Studies (BA)",
"Japanese Studies (BA)",
"Jewish Studies (BA)",
"Justice and Law (BA)",
"Language and Area Studies: French/Europe (BA)",
"Language and Area Studies: German/Europe (BA)",
"Language and Area Studies: Russian/Area Studies (BA)",
"Language and Area Studies: Spanish/Latin America (BA)",
"Legal Studies (BA)",
"Liberal Studies (BA)",
"Literature (BA)",
"Mathematics (BS)",
"Mathematics and Economics (BS) [CAS/ECON]",
"Mathematics and Economics (BS) [CAS/MATH]",
"Music (BA)",
"Musical Theatre (BA)",
"Neuroscience (BS)",
"Philosophy (BA)",
"Photography (BA) [CAS/ART]",
"Photography (BA) [SOC]",
"Physics (BA)",
"Physics (BS)",
"Political Science (BA)",
"Popular Music Performance and Enterprise (BA)",
"Psychology (BA)",
"Public Health (BA)",
"Public Health (BS)",
"Public Relations & Strategic Communication (BA)",
"Religious Studies (BA)",
"Russian Studies (BA)",
"Sociology (BA)",
"Spanish Studies (BA)",
"Statistics (BS)",
"Studio Art (BA)",
"Theatre (BA)",
"Women’s, Gender, and Sexuality Studies (BA)"
]